---
- name: pre_infomation
  hosts: awsissw2
  gather_facts: true
  become: yes
  
  #vars:
    User_Name: itoh_user
    User_Password: zaq12wsx
    User_Group: issw2
  
  tasks:
    - name: create user
      user:
        name: "{{ User_Name }}"
        password: "{{ User_Password }}"
        groups:  "{{ User_Group }}"
        shell: /bin/bash
