---
- name: pre_infomation
  hosts: awsissw2
  gather_facts: true
  become: yes
  
  #vars:
    item.name: itoh_user
    item.password: zaq12wsx
    item.group: issw2
  
  tasks:
    - name: create user
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups:  "{{ item.group }}"
        shell: /bin/bash
